[package]
name = "random_code"
version = "0.1.0"
authors = ["Sooraj <soorajkarthik15@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
chrono = "0.4.11"